### ISSUE TITLE
Make Remove Selection more Findable

### ISSUE THREAD

**Issue by bilalsal** [mawo87/scats#1]
Some users might not notice the "Remove Selection" button.

The button's background should be same as selection color, and the text should be white to support readability.
When no elements are selected, the button should be grayed out disabled.
When a selection is created, the button should be enabled.
![selectionbutton](https://cloud.githubusercontent.com/assets/3834295/7477179/6d9e6c10-f352-11e4-90ee-e7d51f514d72.png)

**Comment by mawo87** [comment]
makes sense. will implement
