### ISSUE TITLE
Show consistent tooltip information about the cells

### ISSUE THREAD

**Issue by bilalsal** [mawo87/scats#3]
Currently, when hovering a composite cell, you show a bar chart of the degrees titled "Shared items / degree", while when hovering an atomic cell, you show the number of elements in a tooltip titled "Items shared with X other sets: N".
I would change both tooltip to be consistent and richer information as follows:
- for atomic cells
  "80 elements shared with 4 other sets.
  20 elements selected (25%)".
- for composite cells
  "80 elements shared with 4 to 9 other sets.
  20 elements selected (25%)".
  IMO, there is need for the bar chart, as at the aggregated level people do not need this information.
  When needed, users can retrieve this information when expanding respective row in scats.
  ![tooltips](https://cloud.githubusercontent.com/assets/3834295/7478051/39d5995c-f358-11e4-9502-0c66d5f9237e.png)

**Comment by mawo87** [comment]
Fixed in commit https://github.com/mawo87/scats/commit/1f84d9bb8e16463cf55ace94d46f02d0e68f0be4
