### ISSUE TITLE
Selection ring is showing the wrong information

### ISSUE THREAD

**Issue by bilalsal** [mawo87/scats#5]
Currently, the selection ring seems to show how many elements in the respective cell divided by the number of elements in the selection.
It should alternatively show how many elements in the respective cell divided by the number of elements in the cell.
As example, when selecting a comoposite cell, all its subcells should be FULLY selected, as all elements in them are contained in the selection

![selectionbug](https://cloud.githubusercontent.com/assets/3834295/7502822/0ce861da-f43f-11e4-885f-21aa8d86ae76.png)

**Comment by mawo87** [comment]
Thanks for the note - can you please update the attached picture? (unfortunately it's broken)

**Comment by bilalsal** [comment]
done!

**Comment by mawo87** [comment]
Great, thx!

Not quite sure if I fully understand ;)

Let's look at the following example:
I have selected degree 4 of element u_20:
![vis_1](https://cloud.githubusercontent.com/assets/1770915/7502862/5a25edf0-f43f-11e4-9e19-669645db9325.png)

The elements in this selection are:
![table_1](https://cloud.githubusercontent.com/assets/1770915/7502878/7dc5f25a-f43f-11e4-828e-ea1d268863e8.png)

When I now hover over degree 4 in set u_9, this is what I will get after solving this issue:
6 elements shared with 4 other sets. 6 elements selected (16.666666666666664%).

To test, I selected degree 4 of set u_9 afterwards:
![vis_2](https://cloud.githubusercontent.com/assets/1770915/7502929/db4641b4-f43f-11e4-8b0a-b17913f88fef.png)
![table_2](https://cloud.githubusercontent.com/assets/1770915/7502935/e73a77e2-f43f-11e4-9a79-84ca68af87f4.png)

Is this correct now?

**Comment by mawo87** [comment]
For explanation:
Previously I computed the selection ring as follows:
result = intersection.length / b.length \* 100;

with:
a = current element (i.e., any arbitrary subset which is in relation to the reference element)
b = reference element (i.e., the selection = a list of elements)
intersection = intersect(a, b);

now I've change the computation to the following:
result = b.length / a.length \* 100;

**Comment by bilalsal** [comment]
Afte rselecting a subst B, the result for an arbitrary set A (e.g. degree 4 in u_9) should be:
 result = intersect(A, B).length / A.length \* 100;

In your example,  you selected the subset B = "degree 4 of set u_20" which contains in 1 element B = {t_1350}.
It seems that you highlight this selection in set A = "degree 4 of set u_9" correctly: A contains 6 elements (i.e. |A| = 6), out of which only 1 belonsg to B.
So intersect(A, B) = {t_1350} and also has length of 1.
The ratio (Anteil) of A that belongs to the selection is hence equal to intersect(A, B) / A.length = 1 / 6 (which seems to be what you show in the partial blue ring of u_9.
But I expect the tooltip to read
" 6 elements shared with 4 other sets.
1 elements selected (16.666666666666664%)."

**Comment by mawo87** [comment]
Thanks for the note.
Just fixed this in commit https://github.com/mawo87/scats/commit/1f84d9bb8e16463cf55ace94d46f02d0e68f0be4
